### ISSUE TITLE
Possible to use in university research?

### ISSUE THREAD

**Issue by StevenChanMD** [jromero/android-unispeech#3]
Hi jromero,

Could we contract your help to modify this code to work for a university project? Our group at UC Davis is looking at using your work for medical interpretation in hospitals and clinics. I couldn't find an e-mail contact for you, but let me know what you think.

Thanks!

Steven Chan
University of California, Davis School of Medicine

**Comment by jromero** [comment]
No comment. Very late of course but I hold no objection.
